import GridApi from "./grid/GridApi";
import FormApi from "./form/FormApi";

declare const Fancy : {
  DEBUG: boolean;
  defineTheme(themeName: string, params: object): void;
  defineControl(controlName, params: object): void;
  defineController(controlName, params: object): void;
  getWidget(id: string): GridApi | FormApi;
  currency: {
    AUD: string;
    BRL: string;
    CAD: string;
    CNY: string;
    CZK: string;
    DKK: string;
    EUR: string;
    GBP: string;
    IDR: string;
    JPY: string;
    KRW: string;
    NOK: string;
    PLN: string;
    RUB: string;
    SEK: string;
    TRY: string;
    USD: string;
  };
  COLORS: string[];
  key: {
    A: number;
    ALT: number;
    B: number;
    BACKSPACE: number;
    C: number;
    CAPS_LOCK: number;
    CONTEXT_MENU: number;
    CTRL: number;
    D: number;
    DELETE: number;
    DOT: number;
    DOWN: number;
    E: number;
    EIGHT: number;
    END: number;
    ENTER: number;
    ESC: number;
    F: number;
    F1: number;
    F2: number;
    F3: number;
    F4: number;
    F5: number;
    F6: number;
    F7: number;
    F8: number;
    F9: number;
    F10: number;
    F11: number;
    F12: number;
    FIVE: number;
    FOUR: number;
    G: number;
    H: number;
    HOME: number;
    I: number;
    INSERT: number;
    J: number;
    K: number;
    L: number;
    LEFT: number;
    M: number;
    META: number;
    N: number;
    NINE: number;
    NUM_DIVISION: number;
    NUM_DOT: number;
    NUM_EIGHT: number;
    NUM_FIVE: number;
    NUM_FOUR: number;
    NUM_MINUS: number;
    NUM_MULTIPLY: number;
    NUM_NINE: number;
    NUM_ONE: number;
    NUM_PLUS: number;
    NUM_SEVEN: number;
    NUM_SIX: number;
    NUM_THREE: number;
    NUM_TWO: number;
    NUM_ZERO: number;
    O: number;
    ONE: number;
    P: number;
    PAGE_DOWN: number;
    PAGE_UP: number;
    PAUSE: number;
    PRINT_SCREEN: number;
    Q: number;
    R: number;
    RETURN: number;
    RIGHT: number;
    S: number;
    SEVEN: number;
    SHIFT: number;
    SIX: number;
    SPACE: number;
    T: number;
    TAB: number;
    THREE: number;
    TWO: number;
    U: number;
    UP: number;
    V: number;
    W: number;
    WHEEL_SCALE: number;
    X: number;
    Y: number;
    Z: number;
    ZERO: number;
  },
  version: string;
}

export default Fancy;